# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJvySCG2LfSsEpQU3QZaJgEjgRUxKAtz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

filename = 'modelo-class.pkl'
modelo, label_encoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

!pip install streamlit
import streamlit as st

st.title('Predicción de Ataque al Corazón (Stroke)')

age = st.slider('Edad', min_value=1, max_value=82, value=40, step=1)
avg_glucose_level = st.number_input('Nivel promedio de glucosa', min_value=50.0, max_value=300.0, value=100.0, step=0.1)
hypertension = st.selectbox('Hipertensión', ['No', 'Yes'])
heart_disease = st.selectbox('Enfermedad cardíaca', ['No', 'Yes'])
ever_married = st.selectbox('¿Alguna vez casado/a?', ['No', 'Yes'])
smoking_status = st.selectbox('Estado de fumador', ["Unknown", "'never smoked'", "'formerly smoked'", "smokes"])

# Dataframe
datos = [[age, hypertension, heart_disease, ever_married, avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level', 'smoking_status'])

data_preparada = data.copy()

data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status', 'hypertension', 'heart_disease', 'ever_married'], drop_first=False, dtype=int)

data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

data_preparada[['age', 'avg_glucose_level']] = min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])

"""# **Predicción**"""

Y_pred = modelo.predict(data_preparada)
Y_pred_label = label_encoder.inverse_transform(Y_pred)
print(Y_pred_label)

data['Prediccion'] = Y_pred_label
st.dataframe(data)

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 11%")